// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: qmdsr/v1/admin.proto

package qmdsrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_qmdsr_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qmdsr_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_qmdsr_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type OpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpResponse) Reset() {
	*x = OpResponse{}
	mi := &file_qmdsr_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpResponse) ProtoMessage() {}

func (x *OpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qmdsr_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpResponse.ProtoReflect.Descriptor instead.
func (*OpResponse) Descriptor() ([]byte, []int) {
	return file_qmdsr_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *OpResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OpResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *OpResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type CollectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Mask          string                 `protobuf:"bytes,3,opt,name=mask,proto3" json:"mask,omitempty"`
	Files         int32                  `protobuf:"varint,4,opt,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionInfo) Reset() {
	*x = CollectionInfo{}
	mi := &file_qmdsr_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfo) ProtoMessage() {}

func (x *CollectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_qmdsr_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfo.ProtoReflect.Descriptor instead.
func (*CollectionInfo) Descriptor() ([]byte, []int) {
	return file_qmdsr_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CollectionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectionInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CollectionInfo) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

func (x *CollectionInfo) GetFiles() int32 {
	if x != nil {
		return x.Files
	}
	return 0
}

type CollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*CollectionInfo      `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionsResponse) Reset() {
	*x = CollectionsResponse{}
	mi := &file_qmdsr_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionsResponse) ProtoMessage() {}

func (x *CollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qmdsr_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionsResponse.ProtoReflect.Descriptor instead.
func (*CollectionsResponse) Descriptor() ([]byte, []int) {
	return file_qmdsr_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *CollectionsResponse) GetCollections() []*CollectionInfo {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *CollectionsResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CollectionsResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_qmdsr_v1_admin_proto protoreflect.FileDescriptor

const file_qmdsr_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x14qmdsr/v1/admin.proto\x12\bqmdsr.v1\x1a\x1bgoogle/protobuf/empty.proto\"$\n" +
	"\fEmbedRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"p\n" +
	"\n" +
	"OpResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\"b\n" +
	"\x0eCollectionInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04mask\x18\x03 \x01(\tR\x04mask\x12\x14\n" +
	"\x05files\x18\x04 \x01(\x05R\x05files\"\x8b\x01\n" +
	"\x13CollectionsResponse\x12:\n" +
	"\vcollections\x18\x01 \x03(\v2\x18.qmdsr.v1.CollectionInfoR\vcollections\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs2\xbc\x02\n" +
	"\fAdminService\x127\n" +
	"\aReindex\x12\x16.google.protobuf.Empty\x1a\x14.qmdsr.v1.OpResponse\x125\n" +
	"\x05Embed\x12\x16.qmdsr.v1.EmbedRequest\x1a\x14.qmdsr.v1.OpResponse\x12:\n" +
	"\n" +
	"CacheClear\x12\x16.google.protobuf.Empty\x1a\x14.qmdsr.v1.OpResponse\x12D\n" +
	"\vCollections\x12\x16.google.protobuf.Empty\x1a\x1d.qmdsr.v1.CollectionsResponse\x12:\n" +
	"\n" +
	"MCPRestart\x12\x16.google.protobuf.Empty\x1a\x14.qmdsr.v1.OpResponseB\x1aZ\x18qmdsr/pb/qmdsrv1;qmdsrv1b\x06proto3"

var (
	file_qmdsr_v1_admin_proto_rawDescOnce sync.Once
	file_qmdsr_v1_admin_proto_rawDescData []byte
)

func file_qmdsr_v1_admin_proto_rawDescGZIP() []byte {
	file_qmdsr_v1_admin_proto_rawDescOnce.Do(func() {
		file_qmdsr_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qmdsr_v1_admin_proto_rawDesc), len(file_qmdsr_v1_admin_proto_rawDesc)))
	})
	return file_qmdsr_v1_admin_proto_rawDescData
}

var file_qmdsr_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_qmdsr_v1_admin_proto_goTypes = []any{
	(*EmbedRequest)(nil),        // 0: qmdsr.v1.EmbedRequest
	(*OpResponse)(nil),          // 1: qmdsr.v1.OpResponse
	(*CollectionInfo)(nil),      // 2: qmdsr.v1.CollectionInfo
	(*CollectionsResponse)(nil), // 3: qmdsr.v1.CollectionsResponse
	(*emptypb.Empty)(nil),       // 4: google.protobuf.Empty
}
var file_qmdsr_v1_admin_proto_depIdxs = []int32{
	2, // 0: qmdsr.v1.CollectionsResponse.collections:type_name -> qmdsr.v1.CollectionInfo
	4, // 1: qmdsr.v1.AdminService.Reindex:input_type -> google.protobuf.Empty
	0, // 2: qmdsr.v1.AdminService.Embed:input_type -> qmdsr.v1.EmbedRequest
	4, // 3: qmdsr.v1.AdminService.CacheClear:input_type -> google.protobuf.Empty
	4, // 4: qmdsr.v1.AdminService.Collections:input_type -> google.protobuf.Empty
	4, // 5: qmdsr.v1.AdminService.MCPRestart:input_type -> google.protobuf.Empty
	1, // 6: qmdsr.v1.AdminService.Reindex:output_type -> qmdsr.v1.OpResponse
	1, // 7: qmdsr.v1.AdminService.Embed:output_type -> qmdsr.v1.OpResponse
	1, // 8: qmdsr.v1.AdminService.CacheClear:output_type -> qmdsr.v1.OpResponse
	3, // 9: qmdsr.v1.AdminService.Collections:output_type -> qmdsr.v1.CollectionsResponse
	1, // 10: qmdsr.v1.AdminService.MCPRestart:output_type -> qmdsr.v1.OpResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_qmdsr_v1_admin_proto_init() }
func file_qmdsr_v1_admin_proto_init() {
	if File_qmdsr_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qmdsr_v1_admin_proto_rawDesc), len(file_qmdsr_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qmdsr_v1_admin_proto_goTypes,
		DependencyIndexes: file_qmdsr_v1_admin_proto_depIdxs,
		MessageInfos:      file_qmdsr_v1_admin_proto_msgTypes,
	}.Build()
	File_qmdsr_v1_admin_proto = out.File
	file_qmdsr_v1_admin_proto_goTypes = nil
	file_qmdsr_v1_admin_proto_depIdxs = nil
}
