// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: qmdsr/v1/admin.proto

package qmdsrv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_Reindex_FullMethodName     = "/qmdsr.v1.AdminService/Reindex"
	AdminService_Embed_FullMethodName       = "/qmdsr.v1.AdminService/Embed"
	AdminService_CacheClear_FullMethodName  = "/qmdsr.v1.AdminService/CacheClear"
	AdminService_Collections_FullMethodName = "/qmdsr.v1.AdminService/Collections"
	AdminService_MCPRestart_FullMethodName  = "/qmdsr.v1.AdminService/MCPRestart"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	Reindex(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OpResponse, error)
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*OpResponse, error)
	CacheClear(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OpResponse, error)
	Collections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CollectionsResponse, error)
	MCPRestart(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OpResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) Reindex(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResponse)
	err := c.cc.Invoke(ctx, AdminService_Reindex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*OpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResponse)
	err := c.cc.Invoke(ctx, AdminService_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CacheClear(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResponse)
	err := c.cc.Invoke(ctx, AdminService_CacheClear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Collections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CollectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectionsResponse)
	err := c.cc.Invoke(ctx, AdminService_Collections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) MCPRestart(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResponse)
	err := c.cc.Invoke(ctx, AdminService_MCPRestart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	Reindex(context.Context, *emptypb.Empty) (*OpResponse, error)
	Embed(context.Context, *EmbedRequest) (*OpResponse, error)
	CacheClear(context.Context, *emptypb.Empty) (*OpResponse, error)
	Collections(context.Context, *emptypb.Empty) (*CollectionsResponse, error)
	MCPRestart(context.Context, *emptypb.Empty) (*OpResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) Reindex(context.Context, *emptypb.Empty) (*OpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reindex not implemented")
}
func (UnimplementedAdminServiceServer) Embed(context.Context, *EmbedRequest) (*OpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedAdminServiceServer) CacheClear(context.Context, *emptypb.Empty) (*OpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CacheClear not implemented")
}
func (UnimplementedAdminServiceServer) Collections(context.Context, *emptypb.Empty) (*CollectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Collections not implemented")
}
func (UnimplementedAdminServiceServer) MCPRestart(context.Context, *emptypb.Empty) (*OpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MCPRestart not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_Reindex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Reindex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Reindex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Reindex(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CacheClear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CacheClear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CacheClear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CacheClear(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Collections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Collections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Collections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Collections(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_MCPRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).MCPRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_MCPRestart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).MCPRestart(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qmdsr.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reindex",
			Handler:    _AdminService_Reindex_Handler,
		},
		{
			MethodName: "Embed",
			Handler:    _AdminService_Embed_Handler,
		},
		{
			MethodName: "CacheClear",
			Handler:    _AdminService_CacheClear_Handler,
		},
		{
			MethodName: "Collections",
			Handler:    _AdminService_Collections_Handler,
		},
		{
			MethodName: "MCPRestart",
			Handler:    _AdminService_MCPRestart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qmdsr/v1/admin.proto",
}
