// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: qmdsr/v1/query.proto

package qmdsrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	Mode_MODE_CORE        Mode = 1
	Mode_MODE_BROAD       Mode = 2
	Mode_MODE_DEEP        Mode = 3
	Mode_MODE_AUTO        Mode = 4
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_CORE",
		2: "MODE_BROAD",
		3: "MODE_DEEP",
		4: "MODE_AUTO",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_CORE":        1,
		"MODE_BROAD":       2,
		"MODE_DEEP":        3,
		"MODE_AUTO":        4,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_qmdsr_v1_query_proto_enumTypes[0].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_qmdsr_v1_query_proto_enumTypes[0]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_qmdsr_v1_query_proto_rawDescGZIP(), []int{0}
}

type ServedMode int32

const (
	ServedMode_SERVED_UNSPECIFIED ServedMode = 0
	ServedMode_SERVED_CORE        ServedMode = 1
	ServedMode_SERVED_BROAD       ServedMode = 2
	ServedMode_SERVED_DEEP        ServedMode = 3
)

// Enum value maps for ServedMode.
var (
	ServedMode_name = map[int32]string{
		0: "SERVED_UNSPECIFIED",
		1: "SERVED_CORE",
		2: "SERVED_BROAD",
		3: "SERVED_DEEP",
	}
	ServedMode_value = map[string]int32{
		"SERVED_UNSPECIFIED": 0,
		"SERVED_CORE":        1,
		"SERVED_BROAD":       2,
		"SERVED_DEEP":        3,
	}
)

func (x ServedMode) Enum() *ServedMode {
	p := new(ServedMode)
	*p = x
	return p
}

func (x ServedMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServedMode) Descriptor() protoreflect.EnumDescriptor {
	return file_qmdsr_v1_query_proto_enumTypes[1].Descriptor()
}

func (ServedMode) Type() protoreflect.EnumType {
	return &file_qmdsr_v1_query_proto_enumTypes[1]
}

func (x ServedMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServedMode.Descriptor instead.
func (ServedMode) EnumDescriptor() ([]byte, []int) {
	return file_qmdsr_v1_query_proto_rawDescGZIP(), []int{1}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	RequestedMode Mode                   `protobuf:"varint,2,opt,name=requested_mode,json=requestedMode,proto3,enum=qmdsr.v1.Mode" json:"requested_mode,omitempty"`
	Collections   []string               `protobuf:"bytes,3,rep,name=collections,proto3" json:"collections,omitempty"`
	AllowFallback bool                   `protobuf:"varint,4,opt,name=allow_fallback,json=allowFallback,proto3" json:"allow_fallback,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	TopK          int32                  `protobuf:"varint,6,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	MinScore      float64                `protobuf:"fixed64,7,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	Explain       bool                   `protobuf:"varint,8,opt,name=explain,proto3" json:"explain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_qmdsr_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qmdsr_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_qmdsr_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetRequestedMode() Mode {
	if x != nil {
		return x.RequestedMode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *SearchRequest) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *SearchRequest) GetAllowFallback() bool {
	if x != nil {
		return x.AllowFallback
	}
	return false
}

func (x *SearchRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetMinScore() float64 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *SearchRequest) GetExplain() bool {
	if x != nil {
		return x.Explain
	}
	return false
}

type Hit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Collection    string                 `protobuf:"bytes,5,opt,name=collection,proto3" json:"collection,omitempty"`
	StartLine     int32                  `protobuf:"varint,6,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine       int32                  `protobuf:"varint,7,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hit) Reset() {
	*x = Hit{}
	mi := &file_qmdsr_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hit) ProtoMessage() {}

func (x *Hit) ProtoReflect() protoreflect.Message {
	mi := &file_qmdsr_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hit.ProtoReflect.Descriptor instead.
func (*Hit) Descriptor() ([]byte, []int) {
	return file_qmdsr_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *Hit) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Hit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Hit) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *Hit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Hit) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Hit) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *Hit) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*Hit                 `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	ServedMode    ServedMode             `protobuf:"varint,2,opt,name=served_mode,json=servedMode,proto3,enum=qmdsr.v1.ServedMode" json:"served_mode,omitempty"`
	Degraded      bool                   `protobuf:"varint,3,opt,name=degraded,proto3" json:"degraded,omitempty"`
	DegradeReason string                 `protobuf:"bytes,4,opt,name=degrade_reason,json=degradeReason,proto3" json:"degrade_reason,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	TraceId       string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RouteLog      []string               `protobuf:"bytes,7,rep,name=route_log,json=routeLog,proto3" json:"route_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_qmdsr_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qmdsr_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_qmdsr_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetHits() []*Hit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetServedMode() ServedMode {
	if x != nil {
		return x.ServedMode
	}
	return ServedMode_SERVED_UNSPECIFIED
}

func (x *SearchResponse) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *SearchResponse) GetDegradeReason() string {
	if x != nil {
		return x.DegradeReason
	}
	return ""
}

func (x *SearchResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *SearchResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SearchResponse) GetRouteLog() []string {
	if x != nil {
		return x.RouteLog
	}
	return nil
}

type SearchChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SearchChunk_Hit
	//	*SearchChunk_Summary
	Payload       isSearchChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChunk) Reset() {
	*x = SearchChunk{}
	mi := &file_qmdsr_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChunk) ProtoMessage() {}

func (x *SearchChunk) ProtoReflect() protoreflect.Message {
	mi := &file_qmdsr_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChunk.ProtoReflect.Descriptor instead.
func (*SearchChunk) Descriptor() ([]byte, []int) {
	return file_qmdsr_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *SearchChunk) GetPayload() isSearchChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SearchChunk) GetHit() *Hit {
	if x != nil {
		if x, ok := x.Payload.(*SearchChunk_Hit); ok {
			return x.Hit
		}
	}
	return nil
}

func (x *SearchChunk) GetSummary() *SearchResponse {
	if x != nil {
		if x, ok := x.Payload.(*SearchChunk_Summary); ok {
			return x.Summary
		}
	}
	return nil
}

type isSearchChunk_Payload interface {
	isSearchChunk_Payload()
}

type SearchChunk_Hit struct {
	Hit *Hit `protobuf:"bytes,1,opt,name=hit,proto3,oneof"`
}

type SearchChunk_Summary struct {
	Summary *SearchResponse `protobuf:"bytes,2,opt,name=summary,proto3,oneof"`
}

func (*SearchChunk_Hit) isSearchChunk_Payload() {}

func (*SearchChunk_Summary) isSearchChunk_Payload() {}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_qmdsr_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qmdsr_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_qmdsr_v1_query_proto_rawDescGZIP(), []int{4}
}

type ComponentHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_qmdsr_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_qmdsr_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_qmdsr_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *ComponentHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComponentHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Components    []*ComponentHealth     `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	UptimeSec     int64                  `protobuf:"varint,4,opt,name=uptime_sec,json=uptimeSec,proto3" json:"uptime_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_qmdsr_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qmdsr_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_qmdsr_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetComponents() []*ComponentHealth {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *HealthResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *HealthResponse) GetUptimeSec() int64 {
	if x != nil {
		return x.UptimeSec
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_qmdsr_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qmdsr_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_qmdsr_v1_query_proto_rawDescGZIP(), []int{7}
}

type StatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Version             string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit              string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	LowResourceMode     bool                   `protobuf:"varint,3,opt,name=low_resource_mode,json=lowResourceMode,proto3" json:"low_resource_mode,omitempty"`
	AllowCpuDeepQuery   bool                   `protobuf:"varint,4,opt,name=allow_cpu_deep_query,json=allowCpuDeepQuery,proto3" json:"allow_cpu_deep_query,omitempty"`
	DeepQueryEnabled    bool                   `protobuf:"varint,5,opt,name=deep_query_enabled,json=deepQueryEnabled,proto3" json:"deep_query_enabled,omitempty"`
	VectorEnabled       bool                   `protobuf:"varint,6,opt,name=vector_enabled,json=vectorEnabled,proto3" json:"vector_enabled,omitempty"`
	QueryMaxConcurrency int32                  `protobuf:"varint,7,opt,name=query_max_concurrency,json=queryMaxConcurrency,proto3" json:"query_max_concurrency,omitempty"`
	QueryTimeoutMs      int32                  `protobuf:"varint,8,opt,name=query_timeout_ms,json=queryTimeoutMs,proto3" json:"query_timeout_ms,omitempty"`
	DeepFailTimeoutMs   int32                  `protobuf:"varint,9,opt,name=deep_fail_timeout_ms,json=deepFailTimeoutMs,proto3" json:"deep_fail_timeout_ms,omitempty"`
	DeepNegativeTtlSec  int32                  `protobuf:"varint,10,opt,name=deep_negative_ttl_sec,json=deepNegativeTtlSec,proto3" json:"deep_negative_ttl_sec,omitempty"`
	TraceId             string                 `protobuf:"bytes,11,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_qmdsr_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qmdsr_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_qmdsr_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *StatusResponse) GetLowResourceMode() bool {
	if x != nil {
		return x.LowResourceMode
	}
	return false
}

func (x *StatusResponse) GetAllowCpuDeepQuery() bool {
	if x != nil {
		return x.AllowCpuDeepQuery
	}
	return false
}

func (x *StatusResponse) GetDeepQueryEnabled() bool {
	if x != nil {
		return x.DeepQueryEnabled
	}
	return false
}

func (x *StatusResponse) GetVectorEnabled() bool {
	if x != nil {
		return x.VectorEnabled
	}
	return false
}

func (x *StatusResponse) GetQueryMaxConcurrency() int32 {
	if x != nil {
		return x.QueryMaxConcurrency
	}
	return 0
}

func (x *StatusResponse) GetQueryTimeoutMs() int32 {
	if x != nil {
		return x.QueryTimeoutMs
	}
	return 0
}

func (x *StatusResponse) GetDeepFailTimeoutMs() int32 {
	if x != nil {
		return x.DeepFailTimeoutMs
	}
	return 0
}

func (x *StatusResponse) GetDeepNegativeTtlSec() int32 {
	if x != nil {
		return x.DeepNegativeTtlSec
	}
	return 0
}

func (x *StatusResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_qmdsr_v1_query_proto protoreflect.FileDescriptor

const file_qmdsr_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x14qmdsr/v1/query.proto\x12\bqmdsr.v1\"\x90\x02\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x125\n" +
	"\x0erequested_mode\x18\x02 \x01(\x0e2\x0e.qmdsr.v1.ModeR\rrequestedMode\x12 \n" +
	"\vcollections\x18\x03 \x03(\tR\vcollections\x12%\n" +
	"\x0eallow_fallback\x18\x04 \x01(\bR\rallowFallback\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x05R\ttimeoutMs\x12\x13\n" +
	"\x05top_k\x18\x06 \x01(\x05R\x04topK\x12\x1b\n" +
	"\tmin_score\x18\a \x01(\x01R\bminScore\x12\x18\n" +
	"\aexplain\x18\b \x01(\bR\aexplain\"\xb7\x01\n" +
	"\x03Hit\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x1e\n" +
	"\n" +
	"collection\x18\x05 \x01(\tR\n" +
	"collection\x12\x1d\n" +
	"\n" +
	"start_line\x18\x06 \x01(\x05R\tstartLine\x12\x19\n" +
	"\bend_line\x18\a \x01(\x05R\aendLine\"\x84\x02\n" +
	"\x0eSearchResponse\x12!\n" +
	"\x04hits\x18\x01 \x03(\v2\r.qmdsr.v1.HitR\x04hits\x125\n" +
	"\vserved_mode\x18\x02 \x01(\x0e2\x14.qmdsr.v1.ServedModeR\n" +
	"servedMode\x12\x1a\n" +
	"\bdegraded\x18\x03 \x01(\bR\bdegraded\x12%\n" +
	"\x0edegrade_reason\x18\x04 \x01(\tR\rdegradeReason\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x12\x1b\n" +
	"\troute_log\x18\a \x03(\tR\brouteLog\"q\n" +
	"\vSearchChunk\x12!\n" +
	"\x03hit\x18\x01 \x01(\v2\r.qmdsr.v1.HitH\x00R\x03hit\x124\n" +
	"\asummary\x18\x02 \x01(\v2\x18.qmdsr.v1.SearchResponseH\x00R\asummaryB\t\n" +
	"\apayload\"\x0f\n" +
	"\rHealthRequest\"W\n" +
	"\x0fComponentHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x96\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x129\n" +
	"\n" +
	"components\x18\x02 \x03(\v2\x19.qmdsr.v1.ComponentHealthR\n" +
	"components\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"uptime_sec\x18\x04 \x01(\x03R\tuptimeSec\"\x0f\n" +
	"\rStatusRequest\"\xd1\x03\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12*\n" +
	"\x11low_resource_mode\x18\x03 \x01(\bR\x0flowResourceMode\x12/\n" +
	"\x14allow_cpu_deep_query\x18\x04 \x01(\bR\x11allowCpuDeepQuery\x12,\n" +
	"\x12deep_query_enabled\x18\x05 \x01(\bR\x10deepQueryEnabled\x12%\n" +
	"\x0evector_enabled\x18\x06 \x01(\bR\rvectorEnabled\x122\n" +
	"\x15query_max_concurrency\x18\a \x01(\x05R\x13queryMaxConcurrency\x12(\n" +
	"\x10query_timeout_ms\x18\b \x01(\x05R\x0equeryTimeoutMs\x12/\n" +
	"\x14deep_fail_timeout_ms\x18\t \x01(\x05R\x11deepFailTimeoutMs\x121\n" +
	"\x15deep_negative_ttl_sec\x18\n" +
	" \x01(\x05R\x12deepNegativeTtlSec\x12\x19\n" +
	"\btrace_id\x18\v \x01(\tR\atraceId*Y\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tMODE_CORE\x10\x01\x12\x0e\n" +
	"\n" +
	"MODE_BROAD\x10\x02\x12\r\n" +
	"\tMODE_DEEP\x10\x03\x12\r\n" +
	"\tMODE_AUTO\x10\x04*X\n" +
	"\n" +
	"ServedMode\x12\x16\n" +
	"\x12SERVED_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSERVED_CORE\x10\x01\x12\x10\n" +
	"\fSERVED_BROAD\x10\x02\x12\x0f\n" +
	"\vSERVED_DEEP\x10\x032\x87\x02\n" +
	"\fQueryService\x12;\n" +
	"\x06Search\x12\x17.qmdsr.v1.SearchRequest\x1a\x18.qmdsr.v1.SearchResponse\x12;\n" +
	"\x06Health\x12\x17.qmdsr.v1.HealthRequest\x1a\x18.qmdsr.v1.HealthResponse\x12;\n" +
	"\x06Status\x12\x17.qmdsr.v1.StatusRequest\x1a\x18.qmdsr.v1.StatusResponse\x12@\n" +
	"\fSearchStream\x12\x17.qmdsr.v1.SearchRequest\x1a\x15.qmdsr.v1.SearchChunk0\x01B\x1aZ\x18qmdsr/pb/qmdsrv1;qmdsrv1b\x06proto3"

var (
	file_qmdsr_v1_query_proto_rawDescOnce sync.Once
	file_qmdsr_v1_query_proto_rawDescData []byte
)

func file_qmdsr_v1_query_proto_rawDescGZIP() []byte {
	file_qmdsr_v1_query_proto_rawDescOnce.Do(func() {
		file_qmdsr_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qmdsr_v1_query_proto_rawDesc), len(file_qmdsr_v1_query_proto_rawDesc)))
	})
	return file_qmdsr_v1_query_proto_rawDescData
}

var file_qmdsr_v1_query_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_qmdsr_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_qmdsr_v1_query_proto_goTypes = []any{
	(Mode)(0),               // 0: qmdsr.v1.Mode
	(ServedMode)(0),         // 1: qmdsr.v1.ServedMode
	(*SearchRequest)(nil),   // 2: qmdsr.v1.SearchRequest
	(*Hit)(nil),             // 3: qmdsr.v1.Hit
	(*SearchResponse)(nil),  // 4: qmdsr.v1.SearchResponse
	(*SearchChunk)(nil),     // 5: qmdsr.v1.SearchChunk
	(*HealthRequest)(nil),   // 6: qmdsr.v1.HealthRequest
	(*ComponentHealth)(nil), // 7: qmdsr.v1.ComponentHealth
	(*HealthResponse)(nil),  // 8: qmdsr.v1.HealthResponse
	(*StatusRequest)(nil),   // 9: qmdsr.v1.StatusRequest
	(*StatusResponse)(nil),  // 10: qmdsr.v1.StatusResponse
}
var file_qmdsr_v1_query_proto_depIdxs = []int32{
	0,  // 0: qmdsr.v1.SearchRequest.requested_mode:type_name -> qmdsr.v1.Mode
	3,  // 1: qmdsr.v1.SearchResponse.hits:type_name -> qmdsr.v1.Hit
	1,  // 2: qmdsr.v1.SearchResponse.served_mode:type_name -> qmdsr.v1.ServedMode
	3,  // 3: qmdsr.v1.SearchChunk.hit:type_name -> qmdsr.v1.Hit
	4,  // 4: qmdsr.v1.SearchChunk.summary:type_name -> qmdsr.v1.SearchResponse
	7,  // 5: qmdsr.v1.HealthResponse.components:type_name -> qmdsr.v1.ComponentHealth
	2,  // 6: qmdsr.v1.QueryService.Search:input_type -> qmdsr.v1.SearchRequest
	6,  // 7: qmdsr.v1.QueryService.Health:input_type -> qmdsr.v1.HealthRequest
	9,  // 8: qmdsr.v1.QueryService.Status:input_type -> qmdsr.v1.StatusRequest
	2,  // 9: qmdsr.v1.QueryService.SearchStream:input_type -> qmdsr.v1.SearchRequest
	4,  // 10: qmdsr.v1.QueryService.Search:output_type -> qmdsr.v1.SearchResponse
	8,  // 11: qmdsr.v1.QueryService.Health:output_type -> qmdsr.v1.HealthResponse
	10, // 12: qmdsr.v1.QueryService.Status:output_type -> qmdsr.v1.StatusResponse
	5,  // 13: qmdsr.v1.QueryService.SearchStream:output_type -> qmdsr.v1.SearchChunk
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_qmdsr_v1_query_proto_init() }
func file_qmdsr_v1_query_proto_init() {
	if File_qmdsr_v1_query_proto != nil {
		return
	}
	file_qmdsr_v1_query_proto_msgTypes[3].OneofWrappers = []any{
		(*SearchChunk_Hit)(nil),
		(*SearchChunk_Summary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qmdsr_v1_query_proto_rawDesc), len(file_qmdsr_v1_query_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qmdsr_v1_query_proto_goTypes,
		DependencyIndexes: file_qmdsr_v1_query_proto_depIdxs,
		EnumInfos:         file_qmdsr_v1_query_proto_enumTypes,
		MessageInfos:      file_qmdsr_v1_query_proto_msgTypes,
	}.Build()
	File_qmdsr_v1_query_proto = out.File
	file_qmdsr_v1_query_proto_goTypes = nil
	file_qmdsr_v1_query_proto_depIdxs = nil
}
